name: Test and release

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.x']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[test] coverage[toml]

      - name: Run test suite
        run: |
          # The `pytest-cov` plugin somehow prevents all of the module-level 
          # statements in this package from being counted as covered.  I have 
          # no idea how; maybe because I use pytest within the package itself? 
          # Whatever the reason, I get the correct coverage info when I run 
          # `coverage` directly.
          coverage run -m pytest
          coverage xml

      - name: Report test coverage
        uses: codecov/codecov-action@v3
